export const imageCreations = [
  {
    image: "winding path through a dense forest",
    keywords: ["green", "nature", "mysterious", "adventure", "twists"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "early morning",
    photoStyle: "moody",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "vast desert landscape with sand dunes",
    keywords: ["arid", "barren", "endless", "isolation", "silhouettes"],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "sunset",
    photoStyle: "warm",
    filmType: "black and white",
    cameraSettings: "Aperture: f/11, Shutter Speed: 1/250, ",
  },
  {
    image: "bustling city scene with tall skyscrapers",
    keywords: ["urban", "modern", "busy", "architecture", "reflection"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "midday",
    photoStyle: "vibrant",
    filmType: "slide",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/200, ",
  },
  {
    image: "serene beach with crystal clear blue water",
    keywords: ["coastal", "relaxation", "tropical", "tranquility", "waves"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "early evening",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/120, ",
  },
  {
    image: "vibrant field of blooming flowers",
    keywords: ["colorful", "spring", "fragrant", "blossom", "pollen"],
    cameraType: "DSLR",
    cameraLens: "macro",
    timeOfDay: "morning",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image: "stunning mountain range with snow-capped peaks",
    keywords: ["majestic", "adventure", "grandeur", "serenity", "solitude"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "sunrise",
    photoStyle: "dramatic",
    filmType: "black and white",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "cozy cabin surrounded by a forest",
    keywords: ["rustic", "peaceful", "seclusion", "woodsy", "fireplace"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "evening",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "picturesque waterfall cascading down rocks",
    keywords: ["water", "nature", "powerful", "refreshing", "mist"],
    cameraType: "DSLR",
    cameraLens: "telephoto",
    timeOfDay: "afternoon",
    photoStyle: "sharp",
    filmType: "color",
    cameraSettings: "Aperture: f/11, Shutter Speed: 1/250, ",
  },
  {
    image: "lively street market filled with colorful stalls",
    keywords: ["hustle", "bustle", "culture", "local", "aromas"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200, ",
  },
  {
    image: "dramatic seascape with crashing waves against cliffs",
    keywords: ["ocean", "powerful", "turbulent", "coastal", "spray"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "sunset",
    photoStyle: "dramatic",
    filmType: "black and white",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "charming alleyway in a historic town",
    keywords: [
      "quaint",
      "cobblestone",
      "architecture",
      "nostalgic",
      "lanterns",
    ],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "breathtaking sunset over a calm lake",
    keywords: ["serene", "reflection", "vibrant", "tranquility", "silhouette"],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "sunrise",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/250, ",
  },
  {
    image: "gorgeous vineyard with rows of grapevines",
    keywords: ["vineyard", "agriculture", "bounty", "rustic", "harvest"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "morning",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image: "vibrant street art mural on a city wall",
    keywords: ["urban", "graffiti", "colorful", "creative", "expression"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200, ",
  },
  {
    image: "mystical foggy forest with towering trees",
    keywords: ["enchanting", "ethereal", "mysterious", "fog", "tranquil"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "early morning",
    photoStyle: "moody",
    filmType: "black and white",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "bustling night market illuminated with colorful lights",
    keywords: ["vibrant", "nightlife", "street food", "crowded", "energy"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "dramatic",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "stunning coastal cliff with crashing waves below",
    keywords: ["coastal", "dramatic", "wild", "powerful", "seabirds"],
    cameraType: "DSLR",
    cameraLens: "telephoto",
    timeOfDay: "afternoon",
    photoStyle: "sharp",
    filmType: "color",
    cameraSettings: "Aperture: f/11, Shutter Speed: 1/250, ",
  },
  {
    image: "serene lake surrounded by towering mountains",
    keywords: ["nature", "reflection", "serenity", "tranquil", "wilderness"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "sunset",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/120, ",
  },
  {
    image: "charming cafe with outdoor seating and colorful umbrellas",
    keywords: ["cosy", "relaxation", "cuisine", "lifestyle", "aromatic"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "morning",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image: "peaceful garden with blooming flowers and a tranquil pond",
    keywords: ["serenity", "blossom", "zen", "harmony", "fountain"],
    cameraType: "Mirrorless",
    cameraLens: "macro",
    timeOfDay: "early morning",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "majestic waterfall surrounded by lush greenery",
    keywords: ["nature", "powerful", "refreshing", "serene", "mist"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "moody",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "quaint village nestled in the mountains",
    keywords: ["scenic", "idyllic", "peaceful", "charming", "community"],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "morning",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/11, Shutter Speed: 1/250, ",
  },
  {
    image: "picturesque sunset on a tropical beach",
    keywords: ["tropical", "paradise", "serene", "tranquility", "silhouette"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "sunset",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "bustling marketplace filled with colorful fruits and vegetables",
    keywords: ["vibrant", "local", "fresh", "culture", "aromas"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200, ",
  },
  {
    image: "mystical forest with sunlight filtering through the trees",
    keywords: ["enchanting", "ethereal", "mysterious", "magic", "tranquil"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "dreamy",
    filmType: "black and white",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "vibrant carnival with colorful rides and festive decorations",
    keywords: ["festive", "exciting", "fun", "crowded", "lights"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "dramatic",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "stunning mountain peak covered in snow",
    keywords: ["majestic", "adventure", "serenity", "solitude", "elevation"],
    cameraType: "DSLR",
    cameraLens: "telephoto",
    timeOfDay: "sunrise",
    photoStyle: "sharp",
    filmType: "color",
    cameraSettings: "Aperture: f/11, Shutter Speed: 1/250, ",
  },
  {
    image: "tranquil forest pond with lily pads and colorful fish",
    keywords: ["serenity", "reflection", "calm", "harmony", "nature"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "early morning",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/120, ",
  },
  {
    image: "cozy fireplace with crackling logs and comfortable chairs",
    keywords: ["cozy", "relaxation", "warmth", "comfort", "hygge"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "evening",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "vibrant field of sunflowers stretching as far as the eye can see",
    keywords: ["colorful", "summer", "blooming", "vibrant", "field"],
    cameraType: "Mirrorless",
    cameraLens: "macro",
    timeOfDay: "morning",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image: "majestic mountain range with snow-capped peaks",
    keywords: ["majestic", "scenic", "adventure", "stunning", "landscape"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "sunrise",
    photoStyle: "moody",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "charming cobblestone street lined with colorful houses",
    keywords: ["quaint", "historic", "charming", "architecture", "cobblestone"],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "morning",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/11, Shutter Speed: 1/250, ",
  },
  {
    image: "serene waterfall hidden in the heart of a lush forest",
    keywords: ["serene", "nature", "tranquil", "refreshing", "water"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "afternoon",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "bustling cityscape with illuminated skyscrapers at night",
    keywords: ["bustling", "urban", "nightlife", "lights", "city"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200, ",
  },
  {
    image: "misty forest with towering trees and a mystical ambiance",
    keywords: ["misty", "ethereal", "mysterious", "enchanting", "tranquil"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "early morning",
    photoStyle: "moody",
    filmType: "black and white",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "vibrant flower market filled with blooms of all colors",
    keywords: ["vibrant", "flowers", "colorful", "fragrant", "market"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "dramatic",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "picturesque lighthouse standing tall on a rocky cliff",
    keywords: ["picturesque", "coastal", "scenic", "serene", "lighthouse"],
    cameraType: "DSLR",
    cameraLens: "telephoto",
    timeOfDay: "afternoon",
    photoStyle: "sharp",
    filmType: "color",
    cameraSettings: "Aperture: f/11, Shutter Speed: 1/250, ",
  },
  {
    image: "tranquil lakeside cabin surrounded by lush greenery",
    keywords: ["tranquil", "nature", "serene", "cabin", "reflection"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "sunset",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/120, ",
  },
  {
    image: "cozy bookstore tucked away on a charming street",
    keywords: ["cozy", "books", "charming", "relaxing", "literature"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "morning",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image: "serene waterfall with cascading waters and a natural pool",
    keywords: ["serene", "waterfall", "nature", "tranquil", "swimming"],
    cameraType: "Mirrorless",
    cameraLens: "macro",
    timeOfDay: "early morning",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "vibrant street art mural adorning a city wall",
    keywords: ["vibrant", "urban", "artistic", "colorful", "mural"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "dramatic",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "stunning sunset over a calm lake with silhouetted trees",
    keywords: ["stunning", "sunset", "calm", "serene", "silhouette"],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "sunset",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/11, Shutter Speed: 1/250, ",
  },
  {
    image:
      "peaceful zen garden with meticulously arranged rocks and raked sand",
    keywords: ["peaceful", "zen", "serene", "balance", "garden"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "morning",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "lively street market with bustling crowds and colorful stalls",
    keywords: ["lively", "market", "crowds", "colorful", "street"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200, ",
  },
  {
    image: "majestic cathedral with intricate architectural details",
    keywords: [
      "majestic",
      "historic",
      "architectural",
      "intricate",
      "cathedral",
    ],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "sharp",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "cascading waterfall surrounded by lush green foliage",
    keywords: ["cascading", "waterfall", "nature", "lush", "foliage"],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "morning",
    photoStyle: "moody",
    filmType: "color",
    cameraSettings: "Aperture: f/11, Shutter Speed: 1/250, ",
  },
  {
    image: "lively concert with a band performing on a grand stage",
    keywords: ["lively", "concert", "music", "performance", "stage"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/120, ",
  },
  {
    image: "picturesque vineyard with neatly arranged rows of grapevines",
    keywords: ["picturesque", "vineyard", "scenic", "grapevines", "wine"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "afternoon",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "peaceful beach with golden sand and crystal-clear blue water",
    keywords: ["peaceful", "beach", "serene", "golden", "crystal-clear"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "sunrise",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "An enchanting castle perched on a hilltop surrounded by trees",
    keywords: ["enchanting", "castle", "hilltop", "trees", "magical"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "dramatic",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image:
      "breathtaking view of a canyon with layers of colorful rock formations",
    keywords: [
      "breathtaking",
      "canyon",
      "colorful",
      "rock formations",
      "scenic",
    ],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image:
      "peaceful forest path winding through tall trees and dappled sunlight",
    keywords: ["peaceful", "forest", "path", "tall trees", "dappled sunlight"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "moody",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image:
      "vibrant festival procession with colorful costumes and traditional music",
    keywords: ["vibrant", "festival", "procession", "costumes", "music"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200, ",
  },
  {
    image:
      "tranquil lakeside scene with a wooden dock and reflections in the water",
    keywords: ["tranquil", "lakeside", "wooden dock", "reflections", "serene"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "sunset",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image: "dreamy, foggy morning in a mist-covered valley",
    keywords: ["dreamy", "foggy", "morning", "mist-covered", "valley"],
    cameraType: "DSLR",
    cameraLens: "telephoto",
    timeOfDay: "early morning",
    photoStyle: "moody",
    filmType: "black and white",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image:
      "bustling food market with vendors selling a variety of culinary delights",
    keywords: [
      "bustling",
      "food market",
      "vendors",
      "culinary delights",
      "colorful",
    ],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image:
      "majestic waterfall cascading down a rocky cliff into a turquoise pool",
    keywords: [
      "majestic",
      "waterfall",
      "rocky cliff",
      "turquoise pool",
      "scenic",
    ],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/120, ",
  },
  {
    image: "cozy cafe with rustic decor and warm lighting",
    keywords: ["cozy", "cafe", "rustic decor", "warm lighting", "relaxing"],
    cameraType: "Film",
    cameraLens: "standard",
    timeOfDay: "morning",
    photoStyle: "bright",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image:
      "serene beach during golden hour with soft waves lapping against the shore",
    keywords: ["serene", "beach", "golden hour", "waves", "soft"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "sunset",
    photoStyle: "warm",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "mystical forest with fog creating an ethereal atmosphere",
    keywords: [
      "mystical",
      "forest",
      "fog",
      "ethereal atmosphere",
      "enchanting",
    ],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "early morning",
    photoStyle: "moody",
    filmType: "black and white",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image: "group of friends laughing and enjoying a picnic in the park",
    keywords: ["friends", "laughing", "picnic", "park", "fun"],
    cameraType: "DSLR",
    cameraLens: "portrait",
    timeOfDay: "afternoon",
    photoStyle: "lifestyle",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image: "couple holding hands and walking along a scenic beach at sunset",
    keywords: ["couple", "holding hands", "scenic beach", "sunset", "romantic"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "sunset",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image:
      "group of colleagues collaborating and brainstorming in a modern office",
    keywords: [
      "colleagues",
      "collaborating",
      "brainstorming",
      "modern office",
      "work",
    ],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "professional",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200,",
  },
  {
    image:
      "family enjoying a day at the amusement park, riding roller coasters and eating cotton candy",
    keywords: [
      "family",
      "amusement park",
      "roller coasters",
      "cotton candy",
      "fun",
    ],
    cameraType: "DSLR",
    cameraLens: "telephoto",
    timeOfDay: "afternoon",
    photoStyle: "joyful",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image:
      "group of athletes high-fiving and celebrating a victory on the sports field",
    keywords: [
      "athletes",
      "high-fiving",
      "victory",
      "sports field",
      "teamwork",
    ],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "evening",
    photoStyle: "action",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/500,",
  },
  {
    image: "crowd cheering and waving flags at a music festival",
    keywords: ["crowd", "cheering", "flags", "music festival", "excitement"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/120, ",
  },
  {
    image: "group of friends playing a lively game of beach volleyball",
    keywords: ["friends", "beach volleyball", "game", "fun", "sport"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "dynamic",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/250, ",
  },
  {
    image: "couple dancing romantically under a starry night sky",
    keywords: ["couple", "dancing", "romantic", "starry night sky", "love"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/60, ",
  },
  {
    image: "group of students studying together in a cozy coffee shop",
    keywords: ["students", "studying", "coffee shop", "cozy", "education"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "lifestyle",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200,",
  },
  {
    image: "crowd of people dancing and having fun at a lively street party",
    keywords: ["crowd", "dancing", "fun", "street party", "celebration"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image: "group of friends laughing and enjoying a picnic in the park",
    keywords: ["friends", "laughing", "picnic", "park", "fun"],
    cameraType: "DSLR",
    cameraLens: "portrait",
    timeOfDay: "afternoon",
    photoStyle: "lifestyle",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image: "couple holding hands and walking along a scenic beach at sunset",
    keywords: ["couple", "holding hands", "scenic beach", "sunset", "romantic"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "sunset",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image:
      "group of colleagues collaborating and brainstorming in a modern office",
    keywords: [
      "colleagues",
      "collaborating",
      "brainstorming",
      "modern office",
      "work",
    ],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "midday",
    photoStyle: "professional",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200,",
  },
  {
    image:
      "family enjoying a day at the amusement park, riding roller coasters and eating cotton candy",
    keywords: [
      "family",
      "amusement park",
      "roller coasters",
      "cotton candy",
      "fun",
    ],
    cameraType: "DSLR",
    cameraLens: "telephoto",
    timeOfDay: "afternoon",
    photoStyle: "joyful",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image:
      "group of athletes high-fiving and celebrating a victory on the sports field",
    keywords: [
      "athletes",
      "high-fiving",
      "victory",
      "sports field",
      "teamwork",
    ],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "evening",
    photoStyle: "action",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/500,",
  },
  {
    image: "crowd cheering and waving flags at a music festival",
    keywords: ["crowd", "cheering", "flags", "music festival", "excitement"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/120, ",
  },
  {
    image: "group of friends playing a lively game of beach volleyball",
    keywords: ["friends", "beach volleyball", "game", "fun", "sport"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "dynamic",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/250, ",
  },
  {
    image: "couple dancing romantically under a starry night sky",
    keywords: ["couple", "dancing", "romantic", "starry night sky", "love"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "dreamy",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/60, ",
  },
  {
    image: "group of students studying together in a cozy coffee shop",
    keywords: ["students", "studying", "coffee shop", "cozy", "education"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "lifestyle",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/200,",
  },
  {
    image: "crowd of people dancing and having fun at a lively street party",
    keywords: ["crowd", "dancing", "fun", "street party", "celebration"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "vibrant",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image: "group of friends hiking together in a beautiful mountain landscape",
    keywords: [
      "friends",
      "hiking",
      "mountain landscape",
      "nature",
      "adventure",
    ],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "scenic",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image: "mother and child playing with bubbles in a sunny backyard",
    keywords: ["mother", "child", "playing", "bubbles", "sunny backyard"],
    cameraType: "DSLR",
    cameraLens: "portrait",
    timeOfDay: "afternoon",
    photoStyle: "lifestyle",
    filmType: "color",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250, ",
  },
  {
    image:
      "group of artists painting and sketching together in a picturesque park",
    keywords: [
      "artists",
      "painting",
      "sketching",
      "picturesque park",
      "creativity",
    ],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "creative",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image:
      "futuristic cityscape with tall skyscrapers and neon lights illuminating the streets",
    keywords: [
      "cyberpunk",
      "futuristic",
      "cityscape",
      "skyscrapers",
      "neon lights",
    ],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "cyberpunk",
    filmType: "grainy",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,",
  },
  {
    image:
      "person wearing futuristic cybernetic implants and augmented reality glasses",
    keywords: [
      "cyberpunk",
      "implants",
      "augmented reality",
      "futuristic",
      "technology",
    ],
    cameraType: "DSLR",
    cameraLens: "portrait",
    timeOfDay: "evening",
    photoStyle: "cyberpunk",
    filmType: "color",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100,",
  },
  {
    image:
      "dark alleyway with glowing neon signs and steam rising from the ground",
    keywords: ["cyberpunk", "alleyway", "neon signs", "steam", "atmospheric"],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "cyberpunk",
    filmType: "grainy",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,",
  },
  {
    image: "futuristic hacker typing on a glowing virtual interface",
    keywords: [
      "cyberpunk",
      "hacker",
      "typing",
      "virtual interface",
      "futuristic",
    ],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "cyberpunk",
    filmType: "color",
    cameraSettings: "Aperture: f/2.2, Shutter Speed: 1/125, ",
  },
  {
    image:
      "group of rebels wearing high-tech armor and masks, standing in front of a graffiti-covered wall",
    keywords: ["cyberpunk", "rebels", "high-tech armor", "masks", "graffiti"],
    cameraType: "DSLR",
    cameraLens: "telephoto",
    timeOfDay: "night",
    photoStyle: "cyberpunk",
    filmType: "grainy",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image:
      "futuristic flying car soaring through the night sky with neon lights trailing behind",
    keywords: [
      "cyberpunk",
      "futuristic",
      "flying car",
      "night sky",
      "neon lights",
    ],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "cyberpunk",
    filmType: "grainy",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,",
  },
  {
    image:
      "bustling cyberpunk market filled with stalls selling high-tech gadgets and futuristic fashion",
    keywords: [
      "cyberpunk",
      "market",
      "high-tech gadgets",
      "futuristic fashion",
      "bustling",
    ],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "cyberpunk",
    filmType: "color",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100,",
  },
  {
    image:
      "group of cybernetically enhanced rebels standing atop a skyscraper, overlooking a dystopian city",
    keywords: [
      "cyberpunk",
      "rebels",
      "cybernetic enhancements",
      "skyscraper",
      "dystopian city",
    ],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "night",
    photoStyle: "cyberpunk",
    filmType: "grainy",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image:
      "hacker in a dark room, surrounded by screens displaying lines of code and virtual data",
    keywords: ["cyberpunk", "hacker", "dark room", "code", "virtual data"],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "cyberpunk",
    filmType: "color",
    cameraSettings: "Aperture: f/2.2, Shutter Speed: 1/125, ",
  },
  {
    image:
      "futuristic city at sunset, with flying drones and holographic advertisements lighting up the streets",
    keywords: [
      "cyberpunk",
      "futuristic city",
      "sunset",
      "flying drones",
      "holographic advertisements",
    ],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "sunset",
    photoStyle: "cyberpunk",
    filmType: "grainy",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60,",
  },
  {
    image:
      "cybernetically enhanced street samurai wielding a futuristic energy sword in a dark alley",
    keywords: [
      "cyberpunk",
      "street samurai",
      "cybernetically enhanced",
      "energy sword",
      "dark alley",
    ],
    cameraType: "Mirrorless",
    cameraLens: "telephoto",
    timeOfDay: "night",
    photoStyle: "cyberpunk",
    filmType: "grainy",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/250,",
  },
  {
    image:
      "cybernetic android sitting on a throne of cables and wires, surrounded by a futuristic control room",
    keywords: ["cyberpunk", "android", "cables", "wires", "control room"],
    cameraType: "DSLR",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "cyberpunk",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image:
      "neon-lit cyberpunk street with flying vehicles and holographic billboards lighting up the night",
    keywords: [
      "cyberpunk",
      "neon-lit",
      "street",
      "flying vehicles",
      "holographic billboards",
    ],
    cameraType: "Mirrorless",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "cyberpunk",
    filmType: "grainy",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,",
  },
  {
    image:
      "An augmented reality hacker wearing a visor, typing on a holographic keyboard in a virtual cyberspace",
    keywords: [
      "cyberpunk",
      "augmented reality",
      "hacker",
      "visor",
      "cyberspace",
    ],
    cameraType: "Smartphone",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "cyberpunk",
    filmType: "color",
    cameraSettings: "Aperture: f/2.2, Shutter Speed: 1/125, ",
  },
  {
    image:
      "An underground cyberpunk nightclub with dancers in futuristic outfits and pulsating neon lights",
    keywords: [
      "cyberpunk",
      "nightclub",
      "dancers",
      "futuristic outfits",
      "neon lights",
    ],
    cameraType: "DSLR",
    cameraLens: "telephoto",
    timeOfDay: "night",
    photoStyle: "cyberpunk",
    filmType: "grainy",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100,",
  },
  {
    image: "whimsical, spooky town with crooked houses and twisted trees",
    keywords: ["Tim Burton", "whimsical", "spooky", "town", "crooked houses"],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "twilight",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "peculiar character with pale skin, dark eyes, and exaggerated features in a gloomy cemetery",
    keywords: [
      "Tim Burton",
      "peculiar character",
      "pale skin",
      "gloomy cemetery",
      "exaggerated features",
    ],
    cameraType: "Digital camera",
    cameraLens: "portrait",
    timeOfDay: "evening",
    photoStyle: "Tim Burton-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100,",
  },
  {
    image:
      "haunted mansion with bats flying around and eerie lights glowing through the windows",
    keywords: [
      "Tim Burton",
      "haunted mansion",
      "bats",
      "eerie lights",
      "gloomy",
    ],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60",
  },
  {
    image:
      "quirky, yet creepy doll with button eyes and a mischievous grin in a tattered toy shop",
    keywords: [
      "Tim Burton",
      "quirky",
      "creepy doll",
      "button eyes",
      "tattered toy shop",
    ],
    cameraType: "Digital camera",
    cameraLens: "macro",
    timeOfDay: "evening",
    photoStyle: "Tim Burton-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/2.2, Shutter Speed: 1/125, ",
  },
  {
    image:
      "haunted forest with gnarled trees, fog creeping along the ground, and mysterious shadows",
    keywords: [
      "Tim Burton",
      "haunted forest",
      "gnarled trees",
      "fog",
      "mysterious shadows",
    ],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "twilight",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "whimsical, gothic castle perched on a hill, surrounded by dark clouds and lightning",
    keywords: [
      "Tim Burton",
      "whimsical",
      "gothic castle",
      "dark clouds",
      "lightning",
    ],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "stormy",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "group of odd, but endearing characters in striped clothing and top hats, wandering through a surreal landscape",
    keywords: [
      "Tim Burton",
      "odd characters",
      "striped clothing",
      "top hats",
      "surreal landscape",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "twilight",
    photoStyle: "Tim Burton-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100,",
  },
  {
    image:
      "spooky, animated graveyard scene with tombstones that come to life and dance in the moonlight",
    keywords: ["Tim Burton", "spooky", "animated", "graveyard", "moonlight"],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "macabre, yet enchanting circus tent with twisted performers and eerie music filling the air",
    keywords: [
      "Tim Burton",
      "macabre",
      "enchanting",
      "circus tent",
      "twisted performers",
    ],
    cameraType: "Digital camera",
    cameraLens: "telephoto",
    timeOfDay: "evening",
    photoStyle: "Tim Burton-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image:
      "mazelike, timeworn graveyard with overgrown vines and crumbling tombstones, surrounded by an eerie mist",
    keywords: ["Tim Burton", "mazelike", "timeworn", "graveyard", "eerie mist"],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "twilight",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "whimsical, haunted carnival with vintage rides and colorful tents, illuminated by a full moon",
    keywords: [
      "Tim Burton",
      "whimsical",
      "haunted carnival",
      "vintage rides",
      "full moon",
    ],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "An eerie, timeworn mansion with overgrown ivy, broken windows, and a single flickering candle inside",
    keywords: [
      "Tim Burton",
      "eerie",
      "timeworn mansion",
      "overgrown ivy",
      "flickering candle",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "Tim Burton-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100,",
  },
  {
    image:
      "peculiar, yet enchanting garden filled with misshapen plants and vibrant, otherworldly flowers",
    keywords: [
      "Tim Burton",
      "peculiar",
      "enchanting garden",
      "misshapen plants",
      "otherworldly flowers",
    ],
    cameraType: "Film camera",
    cameraLens: "macro",
    timeOfDay: "twilight",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "mysterious, decrepit toy factory with broken dolls and eerie, wind-up toys scattered throughout",
    keywords: [
      "Tim Burton",
      "mysterious",
      "decrepit toy factory",
      "broken dolls",
      "wind-up toys",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "Tim Burton-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/2.2, Shutter Speed: 1/125, ",
  },
  {
    image:
      "whimsical, tilted clock tower with mismatched clock faces and curiously spinning hands",
    keywords: [
      "Tim Burton",
      "whimsical",
      "tilted clock tower",
      "mismatched clock faces",
      "spinning hands",
    ],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "twilight",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "creepy, abandoned circus tent with tattered, faded banners and a mysterious circus wagon",
    keywords: [
      "Tim Burton",
      "creepy",
      "abandoned circus tent",
      "faded banners",
      "mysterious circus wagon",
    ],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "hauntingly beautiful ghost with flowing white attire and ethereal glow, floating through a misty forest",
    keywords: [
      "Tim Burton",
      "hauntingly beautiful ghost",
      "flowing white attire",
      "ethereal glow",
      "misty forest",
    ],
    cameraType: "Digital camera",
    cameraLens: "portrait",
    timeOfDay: "twilight",
    photoStyle: "Tim Burton-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100,",
  },
  {
    image:
      "twisted, overgrown tree with contorted branches and eerie glowing eyes peering through the darkness",
    keywords: [
      "Tim Burton",
      "twisted tree",
      "overgrown",
      "contorted branches",
      "eerie glowing eyes",
    ],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "night",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "peculiar, yet endearing creature with a misshapen body, large eyes, and a playful demeanor",
    keywords: [
      "Tim Burton",
      "peculiar creature",
      "misshapen body",
      "large eyes",
      "playful demeanor",
    ],
    cameraType: "Digital camera",
    cameraLens: "macro",
    timeOfDay: "evening",
    photoStyle: "Tim Burton-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/2.2, Shutter Speed: 1/125, ",
  },
  {
    image:
      "gothic, spiral staircase illuminated by a single flickering candle, leading to unknown depths",
    keywords: [
      "Tim Burton",
      "gothic",
      "spiral staircase",
      "flickering candle",
      "unknown depths",
    ],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "twilight",
    photoStyle: "Tim Burton-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "portrait of a mysterious woman with a subtle smile, dressed in Renaissance attire",
    keywords: [
      "Leonardo da Vinci",
      "mysterious woman",
      "subtle smile",
      "Renaissance attire",
    ],
    cameraType: "Digital camera",
    cameraLens: "portrait",
    timeOfDay: "daytime",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100, ",
  },
  {
    image:
      "An intricately detailed sketch of a mechanical flying machine with various gears and propellers",
    keywords: [
      "Leonardo da Vinci",
      "intricate sketch",
      "mechanical flying machine",
      "gears",
      "propellers",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "pencil",
    cameraSettings: "",
  },
  {
    image:
      "landscape featuring a river flowing through a lush countryside, with distant mountains and a hazy atmosphere",
    keywords: [
      "Leonardo da Vinci",
      "river",
      "lush countryside",
      "distant mountains",
      "hazy atmosphere",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60,",
  },
  {
    image:
      "close-up study of a human hand, capturing the intricate details of the anatomy",
    keywords: [
      "Leonardo da Vinci",
      "close-up",
      "human hand",
      "anatomy",
      "intricate details",
    ],
    cameraType: "Digital camera",
    cameraLens: "macro",
    timeOfDay: "afternoon",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/125, ",
  },
  {
    image:
      "tableau of a Last Supper scene, with figures gathered around a table, depicting emotions and gestures",
    keywords: [
      "Leonardo da Vinci",
      "Last Supper",
      "tableau",
      "emotions",
      "gestures",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image:
      "study of human anatomy, showcasing the intricate details of skeletal and muscular systems",
    keywords: [
      "Leonardo da Vinci",
      "human anatomy",
      "skeletal system",
      "muscular system",
      "intricate details",
    ],
    cameraType: "Digital camera",
    cameraLens: "macro",
    timeOfDay: "morning",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/125, ",
  },
  {
    image:
      "landscape featuring rolling hills and a serene lake, with a sense of depth and perspective",
    keywords: [
      "Leonardo da Vinci",
      "rolling hills",
      "serene lake",
      "depth",
      "perspective",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60,",
  },
  {
    image:
      "portrait of a young woman with flowing hair and peaceful expression, bathed in soft, diffused light",
    keywords: [
      "Leonardo da Vinci",
      "young woman",
      "flowing hair",
      "peaceful expression",
      "diffused light",
    ],
    cameraType: "Film camera",
    cameraLens: "portrait",
    timeOfDay: "evening",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100,  ",
  },
  {
    image:
      "An observational sketch of flying birds, capturing their graceful motion and formation in the sky",
    keywords: [
      "Leonardo da Vinci",
      "observational sketch",
      "flying birds",
      "graceful motion",
      "formation",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "pencil",
    cameraSettings: "",
  },
  {
    image:
      "detailed study of various plant species, showcasing their unique botanical features",
    keywords: [
      "Leonardo da Vinci",
      "detailed study",
      "plant species",
      "botanical features",
    ],
    cameraType: "Digital camera",
    cameraLens: "macro",
    timeOfDay: "morning",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/125, ",
  },
  {
    image:
      "detailed sketch of a human face, capturing the beauty and complexity of facial features",
    keywords: [
      "Leonardo da Vinci",
      "detailed sketch",
      "human face",
      "facial features",
      "complexity",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "pencil",
    cameraSettings: "",
  },
  {
    image:
      "landscape featuring a grand castle perched on a hilltop, overlooking a vast countryside",
    keywords: [
      "Leonardo da Vinci",
      "grand castle",
      "hilltop",
      "vast countryside",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60,",
  },
  {
    image:
      "study of the human hand in motion, capturing the gestures and movements with precision",
    keywords: [
      "Leonardo da Vinci",
      "human hand",
      "motion",
      "gestures",
      "precision",
    ],
    cameraType: "Digital camera",
    cameraLens: "macro",
    timeOfDay: "evening",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/125, ",
  },
  {
    image:
      "portrait of an elderly figure, showcasing the wisdom and character etched on their face",
    keywords: [
      "Leonardo da Vinci",
      "elderly figure",
      "wisdom",
      "character",
      "etchings",
    ],
    cameraType: "Film camera",
    cameraLens: "portrait",
    timeOfDay: "morning",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "black and white",
    cameraSettings: "Aperture: f/4.5, Shutter Speed: 1/100,  ",
  },
  {
    image:
      "detailed sketch of the human body, highlighting the proportions and beauty of its form",
    keywords: [
      "Leonardo da Vinci",
      "detailed sketch",
      "human body",
      "proportions",
      "beauty",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Leonardo da Vinci-esque",
    filmType: "pencil",
    cameraSettings: "",
  },
  {
    image:
      "serene countryside with rolling green hills, a babbling brook, and cute creatures frolicking",
    keywords: [
      "Hayao Miyazaki",
      "serene countryside",
      "rolling green hills",
      "babbling brook",
      "cute creatures",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60,",
  },
  {
    image:
      "mystical castle floating in the sky with clouds and vibrant colors all around",
    keywords: [
      "Hayao Miyazaki",
      "mystical castle",
      "floating in the sky",
      "clouds",
      "vibrant colors",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image:
      "whimsical underwater world with colorful coral reefs, playful sea creatures, and beautiful sunlight filtering through",
    keywords: [
      "Hayao Miyazaki",
      "underwater world",
      "coral reefs",
      "playful sea creatures",
      "beautiful sunlight",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "daytime",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60,",
  },
  {
    image:
      "floating island in the sky with lush greenery, waterfalls cascading down, and flying creatures soaring",
    keywords: [
      "Hayao Miyazaki",
      "floating island",
      "lush greenery",
      "waterfalls",
      "flying creatures",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60,",
  },
  {
    image:
      "magical forest with ancient trees, mysterious fog, and mythical creatures lurking in the shadows",
    keywords: [
      "Hayao Miyazaki",
      "magical forest",
      "ancient trees",
      "mysterious fog",
      "mythical creatures",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "morning",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60,",
  },
  {
    image:
      "cozy village nestled in the mountains, with quaint houses, winding streets, and a peaceful atmosphere",
    keywords: [
      "Hayao Miyazaki",
      "cozy village",
      "mountains",
      "quaint houses",
      "peaceful atmosphere",
    ],
    cameraType: "Film camera",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,  ",
  },
  {
    image:
      "fantastical garden with vibrant flowers, talking animals, and a mysterious portal leading to another world",
    keywords: [
      "Hayao Miyazaki",
      "fantastical garden",
      "vibrant flowers",
      "talking animals",
      "mysterious portal",
    ],
    cameraType: "Digital camera",
    cameraLens: "macro",
    timeOfDay: "morning",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/125, ",
  },
  {
    image:
      "mythical creature soaring through the sky with majestic wings and a shimmering tail",
    keywords: [
      "Hayao Miyazaki",
      "mythical creature",
      "soaring through the sky",
      "majestic wings",
      "shimmering tail",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "None",
    cameraSettings: "",
  },
  {
    image:
      "hidden waterfall in a lush forest, with crystal-clear waters and fairies dancing in the mist",
    keywords: [
      "Hayao Miyazaki",
      "hidden waterfall",
      "lush forest",
      "crystal-clear waters",
      "fairies dancing",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "afternoon",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60,",
  },
  {
    image:
      "floating city in the sky with intricate architecture, bustling markets, and airships soaring above",
    keywords: [
      "Hayao Miyazaki",
      "floating city",
      "intricate architecture",
      "bustling markets",
      "airships",
    ],
    cameraType: "Digital camera",
    cameraLens: "wide-angle",
    timeOfDay: "evening",
    photoStyle: "Hayao Miyazaki-esque",
    filmType: "color",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60,",
  },
  {
    image:
      "An abstract composition with bold, geometric shapes and vibrant colors",
    keywords: [
      "Pablo Picasso",
      "abstract composition",
      "geometric shapes",
      "vibrant colors",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "cubist portrait of a person, with fragmented features and multiple perspectives",
    keywords: [
      "Pablo Picasso",
      "cubist portrait",
      "fragmented features",
      "multiple perspectives",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "still life composition with objects arranged in unconventional ways and distorted proportions",
    keywords: [
      "Pablo Picasso",
      "still life composition",
      "unconventional arrangements",
      "distorted proportions",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "An expressive painting of a musician playing an instrument, capturing the energy and movement with bold brushstrokes",
    keywords: [
      "Pablo Picasso",
      "expressive painting",
      "musician",
      "energy",
      "movement",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "collage artwork made with various materials, incorporating found objects and abstract forms",
    keywords: [
      "Pablo Picasso",
      "collage artwork",
      "various materials",
      "found objects",
      "abstract forms",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "surreal landscape with distorted perspectives, melting objects, and dreamlike colors",
    keywords: [
      "Pablo Picasso",
      "surreal landscape",
      "distorted perspectives",
      "melting objects",
      "dreamlike colors",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "portrait with exaggerated features and abstract elements, expressing emotions through bold brushstrokes",
    keywords: [
      "Pablo Picasso",
      "exaggerated features",
      "abstract elements",
      "expressive portrait",
      "bold brushstrokes",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "composition of musical instruments intertwined with human forms, merging the worlds of music and art",
    keywords: [
      "Pablo Picasso",
      "musical instruments",
      "human forms",
      "merging art and music",
      "composition",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "still life arrangement of everyday objects, rendered in a playful and abstract manner",
    keywords: [
      "Pablo Picasso",
      "still life arrangement",
      "everyday objects",
      "playful",
      "abstract",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "series of fragmented faces, exploring different angles and perspectives in a cubist style",
    keywords: [
      "Pablo Picasso",
      "fragmented faces",
      "different angles",
      "perspectives",
      "cubist style",
    ],
    cameraType: "None",
    cameraLens: "None",
    timeOfDay: "daytime",
    photoStyle: "Picasso-esque",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "pixel art landscape with vibrant colors, blocky shapes, and nostalgic 8-bit graphics",
    keywords: [
      "pixel art",
      "video game",
      "landscape",
      "vibrant colors",
      "blocky shapes",
    ],
    cameraType: "Digital camera",
    cameraLens: "Standard lens",
    timeOfDay: "daytime",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/60, ",
  },
  {
    image:
      "pixelated character in an action pose, with dynamic movement and retro gaming vibes",
    keywords: [
      "pixel art",
      "video game",
      "character",
      "action pose",
      "retro gaming",
    ],
    cameraType: "Digital camera",
    cameraLens: "Standard lens",
    timeOfDay: "daytime",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/125,",
  },
  {
    image:
      "pixel art cityscape bustling with activity, featuring tall buildings, neon lights, and flying vehicles",
    keywords: [
      "pixel art",
      "video game",
      "cityscape",
      "activity",
      "neon lights",
    ],
    cameraType: "Digital camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "night",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/30,",
  },
  {
    image:
      "pixel art dungeon filled with treasures, monsters, and hidden pathways",
    keywords: ["pixel art", "video game", "dungeon", "treasures", "monsters"],
    cameraType: "Digital camera",
    cameraLens: "Standard lens",
    timeOfDay: "daytime",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/60, ",
  },
  {
    image:
      "pixel art logo design with retro typography and iconic symbols representing a video game brand",
    keywords: [
      "pixel art",
      "logo design",
      "retro typography",
      "symbols",
      "video game brand",
    ],
    cameraType: "Digital camera",
    cameraLens: "Standard lens",
    timeOfDay: "daytime",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/8, Shutter Speed: 1/125,",
  },
  {
    image:
      "pixel art side-scrolling platformer level with various obstacles, power-ups, and colorful backgrounds",
    keywords: [
      "pixel art",
      "video game",
      "side-scrolling platformer",
      "obstacles",
      "power-ups",
    ],
    cameraType: "Digital camera",
    cameraLens: "Standard lens",
    timeOfDay: "daytime",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image:
      "pixel art character selection screen with a variety of unique and distinct characters to choose from",
    keywords: [
      "pixel art",
      "video game",
      "character selection screen",
      "unique characters",
    ],
    cameraType: "Digital camera",
    cameraLens: "Standard lens",
    timeOfDay: "daytime",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/125,",
  },
  {
    image:
      "pixel art boss battle scene with a towering, menacing boss character and intense action",
    keywords: [
      "pixel art",
      "video game",
      "boss battle",
      "menacing boss character",
      "intense action",
    ],
    cameraType: "Digital camera",
    cameraLens: "Standard lens",
    timeOfDay: "night",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/2.8, Shutter Speed: 1/30,",
  },
  {
    image:
      "pixel art racing game track with sharp turns, boost pads, and a cheering crowd in the background",
    keywords: [
      "pixel art",
      "video game",
      "racing game track",
      "sharp turns",
      "boost pads",
    ],
    cameraType: "Digital camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "daytime",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/5.6, Shutter Speed: 1/60, ",
  },
  {
    image:
      "pixel art puzzle game level with interactive blocks, switches, and logic-based challenges",
    keywords: [
      "pixel art",
      "video game",
      "puzzle game level",
      "interactive blocks",
      "logic-based challenges",
    ],
    cameraType: "Digital camera",
    cameraLens: "Standard lens",
    timeOfDay: "daytime",
    photoStyle: "Pixel art",
    filmType: "Digital",
    cameraSettings: "Aperture: f/4, Shutter Speed: 1/60, ",
  },
  {
    image:
      "3D open-world adventure game with lush environments, dynamic weather, and complex quests",
    keywords: [
      "3D game",
      "open-world",
      "adventure",
      "lush environments",
      "dynamic weather",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "day-night cycle",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "side-scrolling 2D platformer game with pixel art graphics, precise controls, and challenging levels",
    keywords: [
      "2D game",
      "side-scrolling platformer",
      "pixel art graphics",
      "precise controls",
      "challenging levels",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Standard lens",
    timeOfDay: "static",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "fast-paced multiplayer shooter game with realistic graphics, intense gunfights, and futuristic weapons",
    keywords: [
      "3D game",
      "multiplayer shooter",
      "realistic graphics",
      "intense gunfights",
      "futuristic weapons",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Telephoto lens",
    timeOfDay: "dynamic",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "strategy game with top-down view, intricate maps, and strategic decision-making",
    keywords: [
      "2D game",
      "strategy",
      "top-down view",
      "intricate maps",
      "strategic decision-making",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "static",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "VR horror game with immersive environments, jump scares, and eerie sound effects",
    keywords: [
      "VR game",
      "horror",
      "immersive environments",
      "jump scares",
      "eerie sound effects",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "static",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "retro-style arcade game with pixel art graphics, addictive gameplay, and high scores",
    keywords: [
      "arcade game",
      "retro-style",
      "pixel art graphics",
      "addictive gameplay",
      "high scores",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Standard lens",
    timeOfDay: "static",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "fantasy RPG game with epic quests, character customization, and magical abilities",
    keywords: [
      "RPG game",
      "fantasy",
      "epic quests",
      "character customization",
      "magical abilities",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "static",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "puzzle-solving adventure game with mind-bending challenges, hidden clues, and atmospheric environments",
    keywords: [
      "adventure game",
      "puzzle-solving",
      "mind-bending challenges",
      "hidden clues",
      "atmospheric environments",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Standard lens",
    timeOfDay: "static",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "racing game with fast cars, thrilling tracks, and multiplayer competition",
    keywords: [
      "racing game",
      "fast cars",
      "thrilling tracks",
      "multiplayer competition",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "dynamic",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "retro-style platformer game with challenging levels, pixel art graphics, and nostalgic music",
    keywords: [
      "2D game",
      "platformer",
      "retro-style",
      "challenging levels",
      "pixel art graphics",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Standard lens",
    timeOfDay: "static",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "stealth action game with intricate levels, stealth mechanics, and strategic takedowns",
    keywords: [
      "stealth game",
      "action",
      "intricate levels",
      "stealth mechanics",
      "strategic takedowns",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Telephoto lens",
    timeOfDay: "dynamic",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "physics-based puzzle game with interactive environments, object manipulation, and creative problem-solving",
    keywords: [
      "puzzle game",
      "physics-based",
      "interactive environments",
      "object manipulation",
      "creative problem-solving",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "static",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "survival horror game with limited resources, intense atmosphere, and relentless enemies",
    keywords: [
      "survival horror",
      "limited resources",
      "intense atmosphere",
      "relentless enemies",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "dynamic",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "cooperative multiplayer game with teamwork-based challenges, online multiplayer, and communication mechanics",
    keywords: [
      "cooperative game",
      "multiplayer",
      "teamwork-based challenges",
      "online multiplayer",
      "communication mechanics",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "static",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "futuristic sci-fi game with advanced technology, immersive world-building, and epic battles",
    keywords: [
      "futuristic game",
      "sci-fi",
      "advanced technology",
      "immersive world-building",
      "epic battles",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Telephoto lens",
    timeOfDay: "dynamic",
    photoStyle: "Video game style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "Wild West-themed open-world game with vast deserts, dusty towns, and thrilling gunfights",
    keywords: [
      "Wild West",
      "open-world",
      "deserts",
      "dusty towns",
      "gunfights",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "day-night cycle",
    photoStyle: "Western style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "Wild West-inspired shooting gallery game with wooden targets, old-west weapons, and fast-paced shooting",
    keywords: [
      "Wild West",
      "shooting gallery",
      "wooden targets",
      "old-west weapons",
      "fast-paced shooting",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Standard lens",
    timeOfDay: "static",
    photoStyle: "Western style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "Wild West-themed strategy game with bandit raids, resource management, and territorial expansion",
    keywords: [
      "Wild West",
      "strategy",
      "bandit raids",
      "resource management",
      "territorial expansion",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "static",
    photoStyle: "Western style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "Wild West adventure game with treasure hunts, horseback riding, and duels at high noon",
    keywords: [
      "Wild West",
      "adventure",
      "treasure hunts",
      "horseback riding",
      "duels",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Standard lens",
    timeOfDay: "day-night cycle",
    photoStyle: "Western style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "Wild West-themed role-playing game with outlaws, saloons, and frontier exploration",
    keywords: [
      "Wild West",
      "role-playing",
      "outlaws",
      "saloons",
      "frontier exploration",
    ],
    cameraType: "Virtual camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "day-night cycle",
    photoStyle: "Western style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "Wild West-inspired photo editing app with filters that recreate the look of old western photographs",
    keywords: [
      "Wild West",
      "photo editing app",
      "filters",
      "old western photographs",
    ],
    cameraType: "Smartphone camera",
    cameraLens: "",
    timeOfDay: "",
    photoStyle: "Western style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "Wild West-themed virtual reality experience with cowboy shootouts, horse riding, and exploring ghost towns",
    keywords: [
      "Wild West",
      "virtual reality",
      "cowboy shootouts",
      "horse riding",
      "ghost towns",
    ],
    cameraType: "Virtual reality camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "day-night cycle",
    photoStyle: "Western style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "Wild West-inspired fashion shoot with cowboy hats, leather boots, and rustic Western clothing",
    keywords: [
      "Wild West",
      "fashion shoot",
      "cowboy hats",
      "leather boots",
      "rustic Western clothing",
    ],
    cameraType: "DSLR camera",
    cameraLens: "Telephoto lens",
    timeOfDay: "golden hour",
    photoStyle: "Fashion style",
    filmType: "",
    cameraSettings: "Aperture priority",
  },
  {
    image:
      "Wild West-themed music video with cowboys, saloon dances, and desert landscapes",
    keywords: [
      "Wild West",
      "music video",
      "cowboys",
      "saloon dances",
      "desert landscapes",
    ],
    cameraType: "Cinema camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "day-night cycle",
    photoStyle: "Cinematic style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "Wild West-inspired painting with cowboys on horseback, majestic canyons, and golden sunsets",
    keywords: [
      "Wild West",
      "painting",
      "cowboys",
      "majestic canyons",
      "golden sunsets",
    ],
    cameraType: "",
    cameraLens: "",
    timeOfDay: "",
    photoStyle: "Painting style",
    filmType: "",
    cameraSettings: "",
  },
  {
    image:
      "photo taken with a film camera in a vintage street scene with classic cars and retro fashion",
    keywords: [
      "film camera",
      "vintage",
      "street scene",
      "classic cars",
      "retro fashion",
    ],
    cameraType: "Film camera",
    cameraLens: "Prime lens",
    timeOfDay: "golden hour",
    photoStyle: "Film photography",
    filmType: "Color film",
    cameraSettings: "Aperture priority",
  },
  {
    image:
      "nature landscape captured on film with vibrant colors, soft focus, and dreamy atmosphere",
    keywords: [
      "film camera",
      "nature landscape",
      "vibrant colors",
      "soft focus",
      "dreamy atmosphere",
    ],
    cameraType: "Film camera",
    cameraLens: "Wide-angle lens",
    timeOfDay: "sunrise",
    photoStyle: "Film photography",
    filmType: "Slide film",
    cameraSettings: "Manual mode",
  },
  {
    image:
      "portrait taken with a film camera in black and white, showcasing dramatic lighting and timeless beauty",
    keywords: [
      "film camera",
      "portrait",
      "black and white",
      "dramatic lighting",
      "timeless beauty",
    ],
    cameraType: "Film camera",
    cameraLens: "Portrait lens",
    timeOfDay: "indoor, controlled lighting",
    photoStyle: "Film photography",
    filmType: "Black and white film",
    cameraSettings: "Shutter priority",
  },
  {
    image:
      "street photography shot captured on film, featuring candid moments, gritty textures, and urban life",
    keywords: [
      "film camera",
      "street photography",
      "candid moments",
      "gritty textures",
      "urban life",
    ],
    cameraType: "Film camera",
    cameraLens: "Standard lens",
    timeOfDay: "daytime",
    photoStyle: "Film photography",
    filmType: "Color negative film",
    cameraSettings: "Program mode",
  },
  {
    image:
      "still life composition photographed on film, showcasing rich colors, fine details, and a nostalgic feel",
    keywords: [
      "film camera",
      "still life",
      "rich colors",
      "fine details",
      "nostalgic",
    ],
    cameraType: "Film camera",
    cameraLens: "Macro lens",
    timeOfDay: "indoor, controlled lighting",
    photoStyle: "Film photography",
    filmType: "Color film",
    cameraSettings: "Manual mode",
  },
];

export const images = imageCreations.map(({ image }) => image);
export const keywords = imageCreations.flatMap(({ keywords }) => keywords);
export const cameraTypes = imageCreations.map(({ cameraType }) => cameraType);
export const cameraLens = imageCreations.map(({ cameraLens }) => cameraLens);
export const timeOfDays = imageCreations.map(({ timeOfDay }) => timeOfDay);
export const photoStyles = imageCreations.map(({ photoStyle }) => photoStyle);
export const filmTypes = imageCreations.map(({ filmType }) => filmType);
export const cameraSettings = imageCreations.map(
  ({ cameraSettings }) => cameraSettings
);

function getRandomElementByIndex(array: string[]) {
  const randomIndex = Math.floor(Math.random() * array.length);
  return array[randomIndex];
}

function getRandomElementsByIndex(array: string[], numElements: number) {
  const randomElements = [];

  for (let i = 0; i < numElements; i++) {
    const randomElement = getRandomElementByIndex(array);
    randomElements.push(randomElement);
  }

  return randomElements;
}

export function getRandomStyle() {
  return {
    image: getRandomElementByIndex(images),
    keywords: getRandomElementsByIndex(keywords, 5),
    cameraType: getRandomElementByIndex(cameraTypes),
    cameraLens: getRandomElementByIndex(cameraLens),
    timeOfDay: getRandomElementByIndex(timeOfDays),
    photoStyle: getRandomElementByIndex(photoStyles),
    filmType: getRandomElementByIndex(filmTypes),
    cameraSettings: getRandomElementByIndex(cameraSettings),
  };
}
