FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6 -y --fix-missing
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 1337

CMD ["python", "app.py"]
